"""Recount every saved candidate graph with the compiled Rust verifier.

Emits a Markdown table (stdout) plus candidates_report.json. The table in
README.md section 5 is generated by this script -- do not hand-edit it.
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def verifier_path() -> Path:
    exe = ".exe" if sys.platform == "win32" else ""
    for p in [
        ROOT / "target" / "release" / f"verifier_64{exe}",
        ROOT / "verifier" / "target" / "release" / f"verifier_64{exe}",
    ]:
        if p.is_file():
            return p
    raise FileNotFoundError("verifier_64 not built; run `make build-verifier`")


def count_str(counts: dict, length: int, n: int) -> str:
    if length > n:
        return "n/a"
    c = counts.get(length)
    if c is None:
        return "?"
    return f"{c['count']}+" if c["capped"] else str(c["count"])


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cap", type=int, default=100000,
                    help="max cycles counted per length (counts at the cap print as 'N+')")
    ap.add_argument("--glob", default="cuda/best_swarm_n*.json")
    args = ap.parse_args()

    vp = verifier_path()
    rows = []
    for f in sorted(ROOT.glob(args.glob), key=lambda p: int("".join(ch for ch in p.stem if ch.isdigit()) or 0)):
        payload = f.read_text(encoding="utf-8")
        proc = subprocess.run([str(vp), "--full", "--cap", str(args.cap)],
                              input=payload, capture_output=True, text=True, timeout=3600)
        if proc.returncode == 2 or not proc.stdout.strip():
            print(f"FAILED {f.name}: {proc.stderr.strip()}", file=sys.stderr)
            continue
        res = json.loads(proc.stdout)
        res["file"] = f.relative_to(ROOT).as_posix()
        rows.append(res)

    out = ROOT / "candidates_report.json"
    out.write_text(json.dumps(rows, indent=2), encoding="utf-8")

    # A bare | inside $...$ is read as a cell delimiter by strict markdown
    # parsers, so the cardinality bars use \lvert / \rvert. Raw string:
    # in a normal string "\r" would be a carriage return.
    header = (r"| Order $n$ | $\lvert E \rvert$ | Regularity | Connected | Girth | Diam | $C_4$ | $C_8$ | "
              "$C_{16}$ | $C_{32}$ | $C_{64}$ | Counterexample | Candidate File |")
    sep = "| " + " | ".join([":---:"] * 13) + " |"
    print(header)
    print(sep)
    for r in rows:
        counts = {c["length"]: c for c in r["counts"]}
        n = r["n"]
        reg = "Cubic ($d=3$)" if r["is_cubic"] else f"min {r['min_degree']} / max {r['max_degree']}"
        print("| **{n}** | {e} | {reg} | {conn} | {g} | {d} | {c4} | {c8} | {c16} | {c32} | {c64} | {ce} | `{f}` |".format(
            n=n, e=r["edges"], reg=reg,
            conn="yes" if r["connected"] else f"no ({r['components']})",
            g=r["girth"], d=r["diameter"] if r["connected"] else "n/a",
            c4=count_str(counts, 4, n), c8=count_str(counts, 8, n),
            c16=count_str(counts, 16, n), c32=count_str(counts, 32, n),
            c64=count_str(counts, 64, n),
            ce="**YES**" if r["counterexample"] else "no", f=r["file"]))

    print(f"\nWrote {out.relative_to(ROOT)} ({len(rows)} candidates, cap={args.cap}).", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
